version: '3.6'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - $PORT:$PORT
    container_name: kkcc-api
    image: khazanaapi:latest
    stdin_open: true

  mongodb:
    container_name: kkcc-db
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - $DATABASE_PORT:27017
    volumes:
      - db:/data/new/mongodb
    stdin_open: true
    tty: true

volumes:
  db: